name: postgresasen-r 
version: v1 
type: instance-secret 
description: read and write ds appysecret for User postgres db
layer: user 
instance-secret:
  type: key-value-properties 
  acl: r 
  data:
    username: "postgres"
    password: "M9h8I5c4lrQwEgoE0NQR8ZIhz"